baseURL = "https://jerr.dev/"
languageCode = "en-us"
title = "Jerr.dev"
theme = "ananke"

[params]
description = "Jeremy's Development Blog"
recent_posts_number = 3
show_reading_time = true
date_format = "2. January 2006"

[params.ananke.social.follow]
networks = ["bluesky", "github", "linkedin", "mastodon"]

[params.ananke.social.share]
sharetext = false
networks = ["email", "bluesky", "linkedin"]

[params.ananke.social.bluesky]
username = "jerr.dev"

[params.ananke.social.github]
username = "jerr0328"

[params.ananke.social.linkedin]
username = "jmayeres"
rel = "me"

[params.ananke.social.mastodon]
profilelink = "https://mastodon.social/@jerr0328"
rel = "me"

# [services]
# [services.rss]
# limit = 10
