[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.107.0"
  HUGO_ENV = "production"

[[headers]]

  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'; default-src 'none'; object-src 'none'; img-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; report-uri https://jerr.report-uri.io/r/d/csp/enforce;"
